'use client'

import { useMemo, useState, type ChangeEvent } from 'react'
import { AppShell } from '@/components/app-shell'
import { CalendarDays, Database, FilePlus2, MapPin, Search, UserRound, X } from 'lucide-react'

const initialRecords = [
  { fileNo: 'RES-2020-1234', particulars: 'Vol 12 / Page 45', type: 'Deed of Assignment', party1: 'Ali Musa', party2: 'Aisha Bala', location: 'Plot 15, Kano GRA', date: '2024-01-16', by: 'Admin' },
  { fileNo: 'COM-2019-5678', particulars: 'Vol 8 / Page 112', type: 'Deed of Lease', party1: 'Kano Traders Ltd', party2: 'Umar Sani', location: 'Shop 22, Kwari Market', date: '2024-02-23', by: 'Yusuf Y.' },
  { fileNo: 'TEMP-0007', particulars: '—', type: 'Power of Attorney', party1: 'Ibrahim Sule', party2: 'Fatima Abdullahi', location: 'Plot 3, Nassarawa', date: '2026-09-08', by: 'Admin' },
  { fileNo: 'IND-2025-0891', particulars: 'Vol 21 / Page 3', type: 'Deed of Mortgage', party1: 'Kano Textiles Ltd', party2: 'First Bank Plc', location: 'Industrial Layout, Sharada', date: '2025-11-02', by: 'Rayyan J.' },
]

const typeTone = (type: string) => type.includes('Assignment') ? 'bg-primary/10 text-primary' : type.includes('Lease') ? 'bg-emerald-500/10 text-emerald-700' : type.includes('Mortgage') ? 'bg-violet-500/10 text-violet-700' : 'bg-amber-500/10 text-amber-700'

export default function PropertyRecordsAssistantPage() {
  const [records, setRecords] = useState(initialRecords)
  const [query, setQuery] = useState('')
  const [open, setOpen] = useState(false)
  const filtered = useMemo(() => records.filter((record) => Object.values(record).some((value) => value.toLowerCase().includes(query.toLowerCase()))), [records, query])
  const today = records.filter((record) => record.date === '2026-09-08').length
  const handleSearch = (event: ChangeEvent<HTMLInputElement>) => setQuery(event.target.value)

  return <AppShell title="Property Records Assistant" subtitle="Legacy Records · Deeds / PRA"><div className="flex flex-col gap-6">
    <div className="flex flex-wrap items-center justify-between gap-4"><p className="text-sm text-muted-foreground">Capture and manage property and instrument records.</p><button type="button" onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground"><FilePlus2 /> Add new property record</button></div>
    <div className="grid gap-4 md:grid-cols-3"><StatCard icon={CalendarDays} label="Daily records" value={today} tone="text-primary" /><StatCard icon={CalendarDays} label="Monthly records" value={87} tone="text-emerald-600" /><StatCard icon={Database} label="Total records" value="1,284" tone="text-violet-600" /></div>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><button type="button" className="rounded-lg border border-border px-3 py-2 text-sm font-medium hover:bg-muted">Import OP</button><button type="button" className="rounded-lg border border-border px-3 py-2 text-sm font-medium hover:bg-muted">PRA/PIC audit</button></div><div className="relative w-full sm:w-80"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={handleSearch} className="h-10 w-full rounded-lg border border-input bg-background pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-ring" placeholder="Search file no, party, location…" /></div></div>
    <section className="overflow-hidden rounded-xl border border-border bg-card shadow-sm"><div className="border-b border-border px-5 py-4"><h2 className="text-base font-semibold">Legacy property records</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-muted/50"><tr>{['S/N', 'File number', 'Reg. particulars', 'Instrument type', 'Party 1', 'Party 2', 'Location', 'Date captured', 'Captured by', 'Actions'].map((heading) => <th key={heading} className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-muted-foreground">{heading}</th>)}</tr></thead><tbody>{filtered.map((record, index) => <tr key={record.fileNo} className="border-t hover:bg-muted/30"><td className="px-4 py-3 text-muted-foreground">{index + 1}</td><td className="px-4 py-3 font-mono text-xs font-medium">{record.fileNo}</td><td className="px-4 py-3">{record.particulars}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${typeTone(record.type)}`}>{record.type}</span></td><td className="px-4 py-3">{record.party1}</td><td className="px-4 py-3">{record.party2}</td><td className="px-4 py-3"><span className="inline-flex items-center gap-1.5"><MapPin className="size-3.5 text-muted-foreground" />{record.location}</span></td><td className="px-4 py-3">{record.date}</td><td className="px-4 py-3"><span className="inline-flex items-center gap-1.5"><UserRound className="size-3.5 text-muted-foreground" />{record.by}</span></td><td className="px-4 py-3"><button type="button" className="rounded-md border border-border px-2.5 py-1.5 text-xs font-medium hover:bg-muted">View</button></td></tr>)}</tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-border px-4 py-3 text-sm text-muted-foreground"><span>Showing {filtered.length} of 1,284 records</span><div className="flex gap-2"><button type="button" disabled className="rounded-md border border-border px-2.5 py-1.5 text-xs disabled:opacity-50">Previous</button><button type="button" className="rounded-md bg-primary px-2.5 py-1.5 text-xs text-primary-foreground">Next</button></div></div></section>
  </div>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-xl rounded-xl border border-border bg-card p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Add new property record</h2><button type="button" onClick={() => setOpen(false)} aria-label="Close"><X /></button></div><p className="mt-4 text-sm text-muted-foreground">The legacy record form is ready for database fields and workflow rules to be connected.</p><button type="button" onClick={() => setOpen(false)} className="mt-6 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Close</button></div></div>}</AppShell>
}

function StatCard({ icon: Icon, label, value, tone }: { icon: typeof Database; label: string; value: string | number; tone: string }) { return <div className="flex items-center gap-4 rounded-xl border border-border bg-card p-5 shadow-sm"><div className={`flex size-11 items-center justify-center rounded-xl bg-muted ${tone}`}><Icon className="size-5" /></div><div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="text-2xl font-bold tracking-tight">{value}</p></div></div> }
