'use client'

import { useMemo, useState } from 'react'
import { X, Upload } from 'lucide-react'

type Props = { onClose: () => void }

export function PrimaryApplicationForm({ onClose }: Props) {
  const [step, setStep] = useState(1)
  const [prefix, setPrefix] = useState('ST-RES')
  const [serial, setSerial] = useState('')
  const currentYear = new Date().getFullYear()
  const generatedFileNumber = useMemo(() => `${prefix}-${currentYear}-${serial.trim().padStart(3, '0') || '___'}`, [prefix, serial, currentYear])
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true" aria-labelledby="primary-application-title">
    <div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-xl border border-border bg-card shadow-xl">
      <div className="flex items-start justify-between border-b border-border p-6"><div><p className="text-xs font-semibold uppercase tracking-wide text-primary">Ministry of Land and Physical Planning</p><h2 id="primary-application-title" className="mt-2 text-xl font-bold text-foreground">Application for Sectional Titling - Main Application</h2><p className="mt-1 text-sm text-muted-foreground">Complete the form below to submit a new primary application for sectional titling.</p></div><button type="button" onClick={onClose} aria-label="Close form" className="rounded-md p-2 text-muted-foreground hover:bg-muted"><X className="size-5" /></button></div>
      <div className="flex items-center gap-3 border-b border-border px-6 py-4 text-sm"><span className="flex size-8 items-center justify-center rounded-full bg-primary text-primary-foreground">1</span><span className={step >= 2 ? 'text-primary' : 'text-muted-foreground'}>Basic Information</span><span className="h-px flex-1 bg-border" /><span className={`flex size-8 items-center justify-center rounded-full ${step >= 2 ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}>2</span><span className="text-muted-foreground">Required Documents</span><span className="h-px flex-1 bg-border" /><span className={`flex size-8 items-center justify-center rounded-full ${step >= 3 ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}>3</span><span className="text-muted-foreground">Review</span></div>
      {step === 1 && <div className="space-y-6 p-6"><fieldset><legend className="mb-3 text-sm font-semibold text-foreground">Applicant Type</legend><div className="flex flex-wrap gap-5 text-sm text-foreground">{['Individual','Corporate Body','Multiple Owners'].map((item) => <label key={item} className="flex items-center gap-2"><input type="radio" name="applicantType" defaultChecked={item === 'Multiple Owners'} />{item}</label>)}</div></fieldset>
        <div className="rounded-lg border border-primary/30 bg-primary/5 p-4"><h3 className="font-semibold text-foreground">File Number Information</h3><p className="mt-1 text-sm text-muted-foreground">Select file number type and enter the details.</p><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="space-y-1 text-sm text-foreground">File Prefix<select value={prefix} onChange={(event) => setPrefix(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-border bg-card px-3"><option value="ST-RES">ST-RES — Residential</option><option value="ST-COM">ST-COM — Commercial</option><option value="ST-MIXED">ST-MIXED — Mixed Use</option><option value="ST-IND">ST-IND — Industrial</option></select><span className="block text-xs text-muted-foreground">Abia sectional titling prefix</span></label><label className="space-y-1 text-sm text-foreground">Year<input value={currentYear} readOnly className="mt-1 h-10 w-full rounded-md border border-border bg-muted px-3" /><span className="block text-xs text-muted-foreground">Automatically uses the current year</span></label><label className="space-y-1 text-sm text-foreground">Serial Number<input value={serial} onChange={(event) => setSerial(event.target.value.replace(/\D/g, '').slice(0, 6))} inputMode="numeric" className="mt-1 h-10 w-full rounded-md border border-border bg-card px-3" placeholder="e.g. 001" /><span className="block text-xs text-muted-foreground">Numeric suffix, padded to 3 digits</span></label></div><div className="mt-4 rounded-md border border-primary/30 bg-primary/5 px-3 py-2 text-sm text-foreground">Generated File Number: <strong className="font-mono text-primary">{generatedFileNumber}</strong><span className="ml-2 text-xs text-muted-foreground">(Abia State format)</span></div></div>
        <div className="grid gap-6 md:grid-cols-3"><div className="space-y-4 md:col-span-2"><h3 className="font-semibold text-foreground">Property Details</h3><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-1 text-sm">Land Use<select className="mt-1 h-10 w-full rounded-md border border-border bg-card px-3"><option>Residential</option><option>Commercial</option><option>Mixed Use</option><option>Industrial</option></select></label><label className="space-y-1 text-sm">Property Type<select className="mt-1 h-10 w-full rounded-md border border-border bg-card px-3"><option>Detached House</option><option>Housing Estate</option><option>Fragmented Layout</option></select></label><label className="space-y-1 text-sm">No. of Units<input type="number" min="1" className="mt-1 h-10 w-full rounded-md border border-border bg-card px-3" placeholder="Enter units" /></label><label className="space-y-1 text-sm">No. of Blocks<input type="number" min="1" className="mt-1 h-10 w-full rounded-md border border-border bg-card px-3" placeholder="Enter blocks" /></label></div></div><div><div className="mb-2 flex items-center justify-between"><label className="text-sm font-semibold">Passport Photo</label><button type="button" className="inline-flex items-center gap-1 rounded-md border border-border px-2 py-1 text-xs"><Upload className="size-3" />Upload</button></div><div className="flex h-40 flex-col items-center justify-center rounded-md border-2 border-dashed border-border text-center text-sm text-muted-foreground">No passport photo uploaded<span className="mt-1 text-xs">JPG or PNG (max. 2MB)</span></div></div></div>
        <label className="space-y-1 text-sm">Comments<textarea rows={3} className="mt-1 w-full rounded-md border border-border bg-card p-3" placeholder="Enter additional comments or information" /></label><div className="flex items-center justify-between"><button type="button" onClick={onClose} className="rounded-md border border-border px-4 py-2 text-sm">Cancel</button><button type="button" onClick={() => setStep(2)} className="rounded-md bg-primary px-5 py-2 text-sm font-semibold text-primary-foreground">Next</button></div></div>}
      {step === 2 && <div className="space-y-5 p-6"><h3 className="font-semibold">Required Documents</h3><div className="grid gap-4 sm:grid-cols-2">{['Survey Plan','Deed of Assignment','Means of Identification','Building Approval'].map((item) => <label key={item} className="flex items-center justify-between rounded-lg border border-border p-4 text-sm"><span>{item}</span><button type="button" className="inline-flex items-center gap-1 rounded-md border border-border px-2 py-1 text-xs"><Upload className="size-3" />Upload</button></label>)}</div><div className="flex justify-between"><button type="button" onClick={() => setStep(1)} className="rounded-md border border-border px-4 py-2 text-sm">Back</button><button type="button" onClick={() => setStep(3)} className="rounded-md bg-primary px-5 py-2 text-sm font-semibold text-primary-foreground">Review</button></div></div>}
      {step === 3 && <div className="space-y-5 p-6"><h3 className="font-semibold">Review Application</h3><div className="rounded-lg border border-border p-4 text-sm text-muted-foreground">Review the applicant, file number, property, owners, and uploaded documents before submitting.</div><div className="flex justify-between"><button type="button" onClick={() => setStep(2)} className="rounded-md border border-border px-4 py-2 text-sm">Back</button><button type="button" onClick={onClose} className="rounded-md bg-primary px-5 py-2 text-sm font-semibold text-primary-foreground">Submit Application</button></div></div>}
    </div>
  </div>
}

