'use client'

import { useMemo, useState } from 'react'
import { CheckCircle2, Clock3, Download, FilePlus2, Folder, RefreshCw, Search, Users, X } from 'lucide-react'
import type { FileStatus, TrackedFile } from '@/lib/file-tracking-data'

const statuses = ['All Files', 'My Files', 'Awaiting Acceptance', "Other Handler's Files", 'Completed'] as const
const priorities = ['All', 'Normal', 'Urgent'] as const

type Props = { files: TrackedFile[]; onRefresh: () => void; onCreate: () => void; onUpdate: (file: TrackedFile) => void }

export function FileLogManager({ files, onRefresh, onCreate, onUpdate }: Props) {
  const [status, setStatus] = useState<(typeof statuses)[number]>('All Files')
  const [priority, setPriority] = useState<(typeof priorities)[number]>('All')
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState<TrackedFile | null>(null)
  const currentUser = 'Current user'
  const counts = { mine: files.filter((file) => file.receivingOfficer === currentUser).length, awaiting: files.filter((file) => file.status === 'Pending').length, other: files.filter((file) => file.receivingOfficer !== currentUser && file.status !== 'Archived').length, completed: files.filter((file) => file.status === 'Archived').length }
  const filtered = useMemo(() => files.filter((file) => {
    const matchesStatus = status === 'All Files' || (status === 'My Files' && file.receivingOfficer === currentUser) || (status === 'Awaiting Acceptance' && file.status === 'Pending') || (status === "Other Handler's Files" && file.receivingOfficer !== currentUser && file.status !== 'Archived') || (status === 'Completed' && file.status === 'Archived')
    return matchesStatus && (priority === 'All' || file.priority === priority) && `${file.id} ${file.reference} ${file.subject} ${file.receivingOfficer}`.toLowerCase().includes(query.toLowerCase())
  }), [files, priority, query, status])
  const cardData = [{ label: 'My Files', value: counts.mine, icon: Folder, tone: 'text-primary bg-primary/10' }, { label: 'Awaiting Acceptance', value: counts.awaiting, icon: Clock3, tone: 'text-primary bg-primary/10' }, { label: "Other Handler's Files", value: counts.other, icon: Users, tone: 'text-destructive bg-destructive/10' }, { label: 'Completed', value: counts.completed, icon: CheckCircle2, tone: 'text-muted-foreground bg-muted' }]

  return <main className="min-h-screen bg-background p-4 text-foreground lg:p-6"><div className="mx-auto max-w-[1440px] space-y-6">
    <section className="rounded-xl border border-border bg-card px-4 py-3"><div className="flex flex-wrap items-center gap-3 text-xs"><span className="uppercase tracking-wider text-muted-foreground">Request mode</span><span className="border-l border-border pl-3 text-muted-foreground">▣ Manual Request</span><span className="rounded-md bg-primary px-3 py-2 font-semibold text-primary-foreground">▣ Digital Request</span></div></section>
    <div className="flex flex-wrap gap-2"><button type="button" onClick={onRefresh} className="inline-flex items-center gap-2 rounded-md border border-border bg-card px-4 py-2 text-sm"><RefreshCw className="size-4" /> Reset Form</button><button type="button" className="rounded-md border border-border bg-card px-4 py-2 text-sm">◉ Preview</button><button type="button" className="inline-flex items-center gap-2 rounded-md border border-primary bg-card px-4 py-2 text-sm text-primary"><Search className="size-4" /> View Requests</button></div>
    <section className="overflow-hidden rounded-xl border border-border bg-card"><div className="flex items-center gap-6 border-b border-border px-6"><button type="button" onClick={onCreate} className="flex items-center gap-2 border-b-2 border-transparent py-4 text-sm text-muted-foreground"><FilePlus2 className="size-4" /> Create File Tracker</button><button type="button" className="flex items-center gap-2 border-b-2 border-primary py-4 text-sm font-medium text-primary"><Folder className="size-4" /> File Tracker Log <span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs">{files.length}</span></button></div>
      <div className="space-y-6 p-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold">All File Tracker Logs</h1><p className="text-sm text-muted-foreground">Track and manage assigned files</p></div><div className="flex items-center gap-3 rounded-lg border border-border px-4 py-3"><Users className="size-8 rounded-full bg-primary/10 p-2 text-primary" /><div><p className="text-sm font-medium">Current Handler</p><p className="text-sm text-muted-foreground">Clement Joseph (You)</p></div></div></header>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cardData.map(({ label, value, icon: Icon, tone }) => <div key={label} className="rounded-lg border border-border p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold text-primary">{value}</p></div><span className={`rounded-full p-3 ${tone}`}><Icon className="size-5" /></span></div><p className="mt-3 text-xs text-muted-foreground">Files currently in this category</p></div>)}</div>
        <section className="rounded-lg border border-border p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-lg font-semibold">Control Panel</h2><p className="text-sm text-muted-foreground">Manage your file trackers and filter results</p></div><div className="flex flex-wrap gap-2"><input type="date" className="rounded-md border border-border bg-background px-3 py-2 text-sm" /><input type="date" className="rounded-md border border-border bg-background px-3 py-2 text-sm" /><button type="button" className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground"><Download className="size-4" /> Export</button><button type="button" onClick={onRefresh} className="inline-flex items-center gap-2 rounded-md border border-border px-4 py-2 text-sm"><RefreshCw className="size-4" /> Refresh</button></div></div><div className="mt-5 grid gap-4 lg:grid-cols-3"><div className="rounded-lg border border-border bg-muted/30 p-4"><label className="text-sm font-medium">File Status Filter<select value={status} onChange={(event) => setStatus(event.target.value as (typeof statuses)[number])} className="mt-3 w-full rounded-md border border-border bg-background px-3 py-2"><option>All Files</option>{statuses.slice(1).map((item) => <option key={item}>{item}</option>)}</select></label><p className="mt-3 text-xs text-muted-foreground">Green: awaiting acceptance · 
          Red: other handlers · 
          Blue: assigned to you · 
          Gray: completed</p></div><div className="rounded-lg border border-border bg-muted/30 p-4"><p className="text-sm font-medium">Priority Filters</p><div className="mt-3 flex flex-wrap gap-2">{priorities.map((item) => <button key={item} type="button" onClick={() => setPriority(item)} className={`rounded-md px-3 py-2 text-xs ${priority === item ? 'bg-primary text-primary-foreground' : 'border border-border bg-background'}`}>{item}</button>)}</div></div><div className="rounded-lg border border-border bg-muted/30 p-4"><label className="text-sm font-medium">Search Files<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by file name, number, or handler..." className="mt-3 w-full rounded-md border border-border bg-background px-3 py-2 text-sm" /></label></div></div></section>
        <section className="overflow-hidden rounded-lg border border-border"><div className="border-b border-border p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">File Log Table</h2><p className="text-sm text-muted-foreground">All file trackers with handler assignment status</p></div><span className="text-sm text-muted-foreground">{filtered.length} files found</span></div><p className="mt-3 text-xs text-muted-foreground">Status Indicators: <span className="text-primary">● Green</span> — within timeline · <span className="text-primary">● Amber</span> — about to timeout · <span className="text-destructive">● Red</span> — overdue</p></div><div className="flex gap-6 border-b border-border px-6"><button type="button" className="border-b-2 border-primary py-4 text-sm text-primary">Active Files <span className="ml-1 rounded-full bg-primary/10 px-2 py-0.5">{filtered.filter((file) => file.status !== 'Archived').length}</span></button><button type="button" className="py-4 text-sm text-muted-foreground">Completed Files <span className="ml-1 rounded-full bg-muted px-2 py-0.5">{filtered.filter((file) => file.status === 'Archived').length}</span></button></div>{filtered.length === 0 ? <div className="m-6 flex min-h-64 flex-col items-center justify-center rounded-lg border border-dashed border-border text-center"><Folder className="size-10 text-muted-foreground" /><h3 className="mt-4 font-semibold">No trackers found</h3><p className="mt-1 text-sm text-muted-foreground">Try adjusting your filters or search terms.</p><button type="button" onClick={onCreate} className="mt-5 rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground">+ Create New Tracker</button></div> : <div className="divide-y divide-border">{filtered.map((file) => <button type="button" key={file.id} onClick={() => setSelected(file)} className="flex w-full flex-wrap items-center justify-between gap-4 p-5 text-left hover:bg-muted/40"><div><p className="font-semibold">{file.id}</p><p className="text-sm text-muted-foreground">{file.subject}</p></div><div className="text-sm">{file.currentOffice}<p className="text-xs text-muted-foreground">{file.status}</p></div></button>)}</div>}</section>
      </div></section>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 p-4"><div className="w-full max-w-lg rounded-xl border border-border bg-card p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">File Details</h2><button type="button" onClick={() => setSelected(null)} aria-label="Close"><X className="size-5" /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Info label="File number" value={selected.id} /><Info label="Current office" value={selected.currentOffice} /><Info label="Receiving officer" value={selected.receivingOfficer} /><Info label="Status" value={selected.status} /></div><button type="button" onClick={() => { onUpdate({ ...selected, status: 'Received' }); setSelected(null) }} className="mt-6 w-full rounded-md bg-primary px-4 py-2 text-primary-foreground">Accept File</button></div></div>}
  </div></main>
}
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div> }
