'use client'

import { useMemo, useState } from 'react'
import { FileText, Receipt, ShieldCheck, WalletCards } from 'lucide-react'

const nav = [
  { id: 'billing', label: 'Billing', icon: WalletCards },
  { id: 'receipt', label: 'Generate Receipt', icon: Receipt },
  { id: 'luc', label: 'Land Use Charge (LUC)', icon: FileText },
  { id: 'tokens', label: 'Transaction Token Control', icon: ShieldCheck },
]

type Payer = { name: string; file: string; location: string }
const payer: Payer = { name: 'KORAMA COVERS INDUSTRIES LIMITED', file: 'LUAC/AB/00501/AB', location: 'Aba South, Abia State' }

export default function RevMPage() {
  const [active, setActive] = useState('billing')
  const [amount, setAmount] = useState('18125')
  const [token, setToken] = useState('REV-AB-00501-2026')
  const [tokenState, setTokenState] = useState('Active')
  const formattedAmount = useMemo(() => Number(amount || 0).toLocaleString('en-NG', { minimumFractionDigits: 2 }), [amount])

  return <main className="min-h-screen bg-muted/30 text-foreground">
    <header className="border-b bg-card"><div className="mx-auto flex max-w-7xl items-center justify-between gap-6 px-6 py-5"><div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">ALAES REV-M</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Revenue management</h1><p className="mt-1 text-sm text-muted-foreground">Simulated billing, Land Use Charge receipts, and transaction token control.</p></div><div className="rounded-lg border bg-muted/40 px-4 py-3 text-right"><p className="text-xs text-muted-foreground">Current module</p><p className="font-semibold">Abia GIS Revenue Desk</p></div></div></header>
    <div className="mx-auto grid max-w-7xl gap-6 px-4 py-6 sm:px-6 lg:grid-cols-[240px_minmax(0,1fr)]">
      <aside className="h-fit rounded-xl border bg-card p-2"><p className="px-3 pb-3 pt-2 text-xs font-semibold uppercase tracking-widest text-muted-foreground">REV-M workflow</p>{nav.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => setActive(id)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm font-medium transition ${active === id ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon className="size-4" />{label}</button>)}</aside>
      <section className="space-y-6">
        {active === 'billing' && <Billing amount={formattedAmount} setAmount={setAmount} payer={payer} onReceipt={() => setActive('receipt')} />}
        {active === 'luc' && <Luc amount={formattedAmount} setAmount={setAmount} payer={payer} onReceipt={() => setActive('receipt')} />}
        {active === 'receipt' && <ReceiptPreview amount={formattedAmount} payer={payer} token={token} />}
        {active === 'tokens' && <TokenControl token={token} setToken={setToken} state={tokenState} setState={setTokenState} />}
      </section>
    </div>
  </main>
}

function Billing({ amount, setAmount, payer, onReceipt }: { amount: string; setAmount: (v: string) => void; payer: Payer; onReceipt: () => void }) {
  return <><PageTitle title="Billing" description="Create and track simulated revenue transactions for land services." /><div className="grid gap-4 md:grid-cols-3"><Stat label="Open assessments" value="24" /><Stat label="Collected today" value="NGN 1,284,500.00" /><Stat label="Pending receipts" value="08" /></div><div className="grid min-w-0 gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="rounded-xl border bg-card p-6"><h2 className="text-lg font-semibold">New revenue transaction</h2><p className="mt-1 text-sm text-muted-foreground">Use this simulation to create a Land Use Charge assessment.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="File number"><input className="input" value={payer.file} readOnly /></Field><Field label="Assessment class"><select className="input"><option>Land Use Charge (LUC)</option><option>Ground rent</option><option>Premium</option></select></Field><Field label="Payer"><input className="input" value={payer.name} readOnly /></Field><Field label="Amount (NGN)"><input className="input" value={amount.replaceAll(',', '')} onChange={(e) => setAmount(e.target.value.replace(/\D/g, ''))} /></Field></div><div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={onReceipt} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Generate receipt</button><button type="button" className="rounded-lg border px-4 py-2 text-sm font-semibold">Save assessment</button></div></div><Summary amount={amount} payer={payer} /></div></>
}

function Luc({ amount, setAmount, payer, onReceipt }: { amount: string; setAmount: (v: string) => void; payer: Payer; onReceipt: () => void }) { return <><PageTitle title="Land Use Charge (LUC)" description="Review the assessment, confirm the payer, and generate a simulated revenue collector receipt." /><div className="rounded-xl border bg-card p-6"><div className="grid gap-5 md:grid-cols-2"><Field label="File number"><input className="input" value={payer.file} readOnly /></Field><Field label="Assessment year"><select className="input"><option>2026</option><option>2025</option></select></Field><Field label="Registered party"><input className="input" value={payer.name} readOnly /></Field><Field label="Charge amount (NGN)"><input className="input" value={amount.replaceAll(',', '')} onChange={(e) => setAmount(e.target.value.replace(/\D/g, ''))} /></Field></div><div className="mt-6 rounded-lg border bg-muted/40 p-4 text-sm"><div className="flex justify-between"><span>Land Use Charge</span><strong>NGN {amount}</strong></div><div className="mt-2 flex justify-between text-muted-foreground"><span>Processing fee</span><span>NGN 0.00</span></div><div className="mt-3 border-t pt-3 flex justify-between font-semibold"><span>Total payable</span><span>NGN {amount}</span></div></div><button type="button" onClick={onReceipt} className="mt-6 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Confirm and generate receipt</button></div></> }

function ReceiptPreview({ amount, payer, token }: { amount: string; payer: Payer; token: string }) { return <><PageTitle title="Generate Receipt" description="Simulation preview based on the Abia GIS revenue collector receipt format." /><div className="flex justify-end"><button type="button" onClick={() => window.print()} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Print receipt</button></div><div className="receipt-paper"><ReceiptCopy label="ORIGINAL" amount={amount} payer={payer} token={token} /><div className="receipt-divider" /><ReceiptCopy label="COPY" amount={amount} payer={payer} token={token} /></div></> }

function ReceiptCopy({ label, amount, payer, token }: { label: string; amount: string; payer: Payer; token: string }) { return <article className="space-y-3 text-[11px] leading-4"><div className="flex items-center justify-between border-b pb-2"><span className="font-bold text-primary">ABIA STATE GEOGRAPHIC INFORMATION SYSTEM (ABIAGIS)</span><span className="font-bold text-red-600">{label}</span></div><div className="grid grid-cols-2 gap-1 border-b pb-2"><span>File Number: <b>{payer.file}</b></span><span>Payment Date: <b>10-Sep-2026</b></span><span>Payment ID: <b>{token}</b></span><span>Receipt Date: <b>10-Sep-2026</b></span></div><p>Received from <b>{payer.name}</b> being payment for Land Use Charge on {payer.location}.</p><div className="border px-2 py-1 font-semibold">the sum of NGN {amount}</div><div className="flex justify-between pt-3 text-[9px] uppercase"><span>Signature or mark of payer</span><span>Signature of revenue collector</span></div><p className="text-center text-[9px] font-semibold">NO REFUND OF MONEY AFTER PAYMENT</p><div className="flex items-end justify-between border-t pt-2"><span className="font-bold text-primary">REVENUE COLLECTOR'S RECEIPT</span><span className="barcode">||||||||||||||||||||||||</span></div></article> }

function TokenControl({ token, setToken, state, setState }: { token: string; setToken: (v: string) => void; state: string; setState: (v: string) => void }) { return <><PageTitle title="Transaction Token Control" description="Issue, validate, and consume tokens for simulated revenue transactions." /><div className="grid min-w-0 gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="rounded-xl border bg-card p-6"><h2 className="text-lg font-semibold">Token control</h2><div className="mt-5 space-y-4"><Field label="Transaction token"><input className="input font-mono" value={token} onChange={(e) => setToken(e.target.value.toUpperCase())} /></Field><Field label="Token state"><select className="input" value={state} onChange={(e) => setState(e.target.value)}><option>Active</option><option>Validated</option><option>Consumed</option><option>Revoked</option></select></Field></div><div className="mt-6 flex flex-wrap gap-2"><button type="button" onClick={() => setState('Validated')} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Validate token</button><button type="button" onClick={() => setState('Consumed')} className="rounded-lg border px-4 py-2 text-sm font-semibold">Consume token</button></div></div><div className="rounded-xl border bg-card p-6"><p className="text-xs uppercase tracking-widest text-muted-foreground">Current token</p><p className="mt-3 break-all font-mono text-lg font-semibold">{token}</p><p className="mt-4 rounded-full bg-muted px-3 py-1 text-center text-sm font-semibold">{state}</p></div></div></> }

function Summary({ amount, payer }: { amount: string; payer: Payer }) { return <div className="rounded-xl border bg-card p-6"><p className="text-xs uppercase tracking-widest text-muted-foreground">Assessment summary</p><p className="mt-4 text-2xl font-semibold">NGN {amount}</p><p className="mt-2 text-sm font-medium">{payer.name}</p><p className="mt-1 text-sm text-muted-foreground">{payer.file}</p></div> }
function PageTitle({ title, description }: { title: string; description: string }) { return <div><h2 className="text-2xl font-semibold tracking-tight">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div> }
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border bg-card p-5"><p className="text-xs uppercase tracking-widest text-muted-foreground">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p></div> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-2 text-sm font-medium">{label}{children}</label> }
