'use client'

import { useMemo, useState } from 'react'
import { Download, Search, Plus, MoreHorizontal } from 'lucide-react'
import { AppShell } from '@/components/app-shell'
import { Button } from '@/components/ui/button'
import { SectionCard, SectionHeader, StatusBadge } from '@/components/system-admin/primitives'

const PAGE_DATA: Record<string, { title: string; description: string; stats: [string,string,string][]; columns: string[]; rows: string[][] }> = {
  onboarding: { title: 'Onboarding Requests', description: 'Review and approve new professional search subscribers.', stats: [['Pending','24','amber'],['Approved this month','86','green'],['Needs review','7','red']], columns: ['Applicant','Organisation','Plan','Submitted','Status'], rows: [['Okezie & Partners','Law Firm','Professional','Today','Pending'],['Abia Surveyors Network','Surveying','Enterprise','Yesterday','Pending'],['Chukwu Legal Services','Law Firm','Starter','12 Jun 2026','Approved'],['Prime Property Consultants','Consultancy','Professional','11 Jun 2026','Needs review']] },
  invoices: { title: 'Pending Invoice', description: 'Track invoices awaiting payment confirmation.', stats: [['Outstanding','₦4.8m','amber'],['Due this week','₦1.2m','red'],['Paid this month','₦8.4m','green']], columns: ['Invoice','Organisation','Amount','Due date','Status'], rows: [['INV-2026-0041','Okezie & Partners','₦420,000','18 Jun 2026','Pending'],['INV-2026-0038','Abia Surveyors Network','₦760,000','20 Jun 2026','Pending'],['INV-2026-0032','Chukwu Legal Services','₦180,000','Paid','Paid']] },
  subscriptions: { title: 'Subscriptions', description: 'Manage active portal subscriptions and plan changes.', stats: [['Active','184','green'],['Expiring soon','12','amber'],['Cancelled','8','red']], columns: ['Organisation','Plan','Tokens left','Renewal','Status'], rows: [['Okezie & Partners','Professional','142','30 Jun 2026','Active'],['Abia Surveyors Network','Enterprise','1,208','31 Dec 2026','Active'],['Chukwu Legal Services','Starter','0','Expired','Expired']] },
  revenue: { title: 'Usage and Revenue', description: 'Monitor search volume, token usage, and revenue.', stats: [['Revenue this month','₦12.6m','green'],['Searches','3,842','blue'],['Tokens consumed','18,402','amber']], columns: ['Period','Searches','Tokens','Revenue','Growth'], rows: [['June 2026','3,842','18,402','₦12.6m','+18.4%'],['May 2026','3,244','15,910','₦10.8m','+12.1%'],['April 2026','2,902','14,220','₦9.6m','+8.7%']] },
  packages: { title: 'Packages', description: 'Configure token packages available to subscribers.', stats: [['Active packages','4','green'],['Most popular','Professional','blue'],['Avg. order','₦186k','amber']], columns: ['Package','Tokens','Price','Subscribers','Status'], rows: [['Starter','25','₦50,000','62','Active'],['Professional','100','₦150,000','94','Active'],['Enterprise','500','₦600,000','28','Active'],['Custom','—','Contact sales','—','Active']] },
  wallets: { title: 'Token Top-up / Wallets', description: 'Review wallet balances and token top-up activity.', stats: [['Total balance','38,420','blue'],['Top-ups today','18','green'],['Low balances','9','amber']], columns: ['Organisation','Balance','Last top-up','Total used','Status'], rows: [['Okezie & Partners','142','14 Jun 2026','1,858','Healthy'],['Chukwu Legal Services','0','02 May 2026','100','Low'],['Abia Surveyors Network','1,208','10 Jun 2026','4,792','Healthy']] },
  legal: { title: 'Legal Department', description: 'Manage legal review queues and official search reports.', stats: [['Open reviews','16','amber'],['Reports issued','248','green'],['Escalations','3','red']], columns: ['File number','Applicant','Request type','Assigned to','Status'], rows: [['LUM/01217','Okezie & Partners','Official search','Legal Desk','In review'],['LUAC/AB/00128/AB','Prime Property Consultants','Certified report','A. Nwosu','Pending'],['LUM/OH/00421','Chukwu Legal Services','Search report','Legal Desk','Issued']] },
  feedback: { title: 'Feedback & Complaints', description: 'Respond to subscriber feedback and service complaints.', stats: [['Open tickets','11','amber'],['Resolved this month','42','green'],['SLA breaches','2','red']], columns: ['Ticket','From','Subject','Received','Status'], rows: [['FB-1042','Okezie & Partners','Search result clarification','Today','Open'],['FB-1038','Public user','Payment confirmation','Yesterday','In progress'],['FB-1031','Abia Surveyors Network','Portal experience','10 Jun 2026','Resolved']] },
}

export function PHSAdminPage({ section }: { section: keyof typeof PAGE_DATA }) {
  const data = PAGE_DATA[section]
  const [query, setQuery] = useState('')
  const rows = useMemo(() => data.rows.filter((row) => !query || row.join(' ').toLowerCase().includes(query.toLowerCase())), [data.rows, query])
  return <AppShell><main className="space-y-6 p-6 lg:p-8"><SectionHeader title={data.title} description={`PHS PORTAL ADMIN · ${data.description}`} actions={<><Button variant="outline" onClick={() => window.print()}><Download className="mr-2 size-4" />Export</Button><Button><Plus className="mr-2 size-4" />Add new</Button></>} /><div className="grid gap-4 md:grid-cols-3">{data.stats.map(([label, value, tone]) => <div key={label} className="rounded-xl border border-border bg-card p-5"><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-sm text-muted-foreground">{label}</p><div className={`mt-3 h-1 w-12 rounded-full ${tone === 'green' ? 'bg-emerald-500' : tone === 'red' ? 'bg-red-500' : tone === 'amber' ? 'bg-amber-500' : 'bg-blue-500'}`} /></div>)}</div><SectionCard><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-4"><div className="relative w-full max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search records..." className="h-10 w-full rounded-lg border border-border bg-background pl-9 pr-3 text-sm outline-none focus:border-primary" /></div><span className="text-sm text-muted-foreground">{rows.length} records</span></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border text-xs uppercase tracking-wide text-muted-foreground">{data.columns.map((column) => <th key={column} className="px-4 py-3 font-medium">{column}</th>)}<th className="px-4 py-3" /></tr></thead><tbody>{rows.map((row, index) => <tr key={`${row[0]}-${index}`} className="border-b border-border last:border-0 hover:bg-muted/30">{row.map((cell, cellIndex) => <td key={`${cell}-${cellIndex}`} className="px-4 py-4">{cellIndex === row.length - 1 ? <StatusBadge tone={cell.toLowerCase().includes('active') || cell.toLowerCase().includes('paid') || cell.toLowerCase().includes('resolved') || cell.toLowerCase().includes('healthy') || cell.toLowerCase().includes('issued') ? 'green' : cell.toLowerCase().includes('review') || cell.toLowerCase().includes('pending') || cell.toLowerCase().includes('low') || cell.toLowerCase().includes('open') ? 'amber' : 'blue'}>{cell}</StatusBadge> : cell}</td>)}<td className="px-4 py-4 text-right"><Button variant="ghost" size="icon" aria-label="More actions"><MoreHorizontal className="size-4" /></Button></td></tr>)}</tbody></table></div></SectionCard></main></AppShell>
}
