'use client'

import { useMemo, useState } from 'react'
import { BarChart3, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Download, FileCheck2, FileText, Plus, Printer, Settings2, UserRound, X } from 'lucide-react'
import { AppShell } from '@/components/app-shell'
import { Avatar, Field, Modal, SearchBar, SelectInput, StatusBadge } from '@/components/system-admin/primitives'
import { FILENO_RECORDS, FILENO_SCHEDULE_RULES, FILENO_SCHEDULES, buildFileNo, landUseTone, type FileNoPrefix, type FileNoSchedule, type FileNoSuffix } from '@/lib/sectional-titling-data'

export default function FileNoManagementPage() {
  const [search, setSearch] = useState('')
  const [landUse, setLandUse] = useState('')
  const [fileType, setFileType] = useState('')
  const [commissionFileType, setCommissionFileType] = useState('')
  const [commissionOpen, setCommissionOpen] = useState(false)
  const [schedule, setSchedule] = useState<FileNoSchedule>('Aba')
  const [prefix, setPrefix] = useState<FileNoPrefix>('LUAC/AB')
  const [suffix, setSuffix] = useState<FileNoSuffix>('AB')
  const [sequence, setSequence] = useState('1')
  const [generated, setGenerated] = useState('')
  const [batchMode, setBatchMode] = useState(false)
  const [batchCount, setBatchCount] = useState('100')
  const [batchApplicant, setBatchApplicant] = useState(0)
  const [batchLocation, setBatchLocation] = useState(0)
  const [page, setPage] = useState(1)
  const pageSize = 20
  const scheduleRule = FILENO_SCHEDULE_RULES[schedule]
  const preview = buildFileNo(prefix, Number(sequence) || 0, suffix)
  const filtered = useMemo(() => FILENO_RECORDS.filter((record) => {
    const query = search.trim().toLowerCase()
    return (!query || [record.mlsFileNo, record.applicant, record.type].join(' ').toLowerCase().includes(query)) && (!landUse || record.landUse === landUse) && (!fileType || record.type === fileType)
  }), [search, landUse, fileType])
  const visible = filtered.slice((page - 1) * pageSize, page * pageSize)
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize))
  const handleScheduleChange = (value: FileNoSchedule) => { setSchedule(value); setPrefix(FILENO_SCHEDULE_RULES[value].prefixes[0]); setSuffix(FILENO_SCHEDULE_RULES[value].suffixes[0] ?? 'AB') }

  return (
    <AppShell title="Land" subtitle="Generate New FileNo (MLSFileNo)" metrics={[]}>
      <div className="min-h-screen bg-muted/30 px-4 py-5 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-[1800px] space-y-6">
          <div className="flex items-end gap-1 border-b border-border">
            <button className="flex items-center gap-3 rounded-t-xl bg-background px-7 py-4 text-lg font-semibold text-foreground shadow-sm"><FileText className="size-6 text-primary" /> MLPP File Number Generator</button>
            <button className="flex items-center gap-3 rounded-t-xl px-7 py-4 text-lg font-semibold text-muted-foreground hover:bg-background/70"><Settings2 className="size-6" /> Serial Initialization</button>
            <button className="flex items-center gap-3 rounded-t-xl px-7 py-4 text-lg font-semibold text-muted-foreground hover:bg-background/70"><FileCheck2 className="size-6" /> Consolidated Report</button>
          </div>

          <div className="grid gap-5 lg:grid-cols-[1.1fr_1.3fr_1.35fr_1.35fr_1.35fr]">
            <button type="button" onClick={() => setCommissionOpen(true)} className="flex min-h-20 items-center justify-center gap-5 rounded-xl bg-primary px-6 text-xl font-medium text-primary-foreground shadow-sm transition hover:bg-primary/90"><Plus className="size-8" /> <span className="max-w-48 text-pretty">Generate New File Number</span></button>
            <button type="button" className="flex min-h-20 items-center justify-center gap-5 rounded-xl bg-chart-2 px-6 text-xl font-medium text-primary-foreground shadow-sm transition hover:opacity-90"><Printer className="size-8" /> <span className="max-w-64 text-pretty">Print Batch Commissioning Sheet</span></button>
            <SummaryCard icon={FileCheck2} label="Total Commissioned" value="6,301" note="Excludes legacy" tone="blue" />
            <SummaryCard icon={CalendarDays} label="Commissioned Today" value="0" note="Sep 9, 2026" tone="green" />
            <SummaryCard icon={BarChart3} label="Commissioned This Month" value="96" note="September 2026" tone="violet" />
          </div>

          <section className="overflow-hidden rounded-xl border border-border bg-background shadow-sm">
            <div className="flex flex-col gap-4 border-b border-border p-5 xl:flex-row xl:items-end xl:justify-between">
              <div className="flex items-end gap-3 text-lg"><span>Show</span><select className="h-11 rounded-md border border-input bg-background px-3"><option>20</option><option>50</option><option>100</option></select><span>file numbers per page</span></div>
              <div className="flex items-center gap-2 text-lg text-muted-foreground"><button type="button" disabled={page === 1} onClick={() => setPage(page - 1)} className="px-3 py-2 disabled:opacity-40">Previous</button>{[1, 2, 3, 4, 5].map((item) => <button key={item} type="button" onClick={() => setPage(item)} className={`size-11 rounded-md ${page === item ? 'border border-primary bg-primary/10 text-primary' : ''}`}>{item}</button>)}<span>...</span><button type="button" onClick={() => setPage(Math.min(totalPages, page + 1))} className="px-3 py-2">Next</button></div>
              <Field label="Search file numbers"><SearchBar value={search} onChange={(value) => { setSearch(value); setPage(1) }} placeholder="Search file numbers..." /></Field>
            </div>
            <div className="flex flex-col gap-3 border-b border-border bg-muted/20 p-5 md:flex-row">
              <div className="flex-1"><Field label="Land Use"><SelectInput value={landUse} onChange={(event) => { setLandUse(event.target.value); setPage(1) }}><option value="">All Land Uses</option><option>Residential</option><option>Commercial</option><option>Industrial</option><option>Mixed-Use</option></SelectInput></Field></div>
              <div className="flex-1"><Field label="File Type"><SelectInput value={fileType} onChange={(event) => { setFileType(event.target.value); setPage(1) }}><option value="">All Types</option><option>Primary</option><option>SuA</option><option>PuA</option></SelectInput></Field></div>
              <button type="button" onClick={() => { setSearch(''); setLandUse(''); setFileType(''); setPage(1) }} className="inline-flex h-10 items-center gap-2 self-end px-3 text-sm text-muted-foreground hover:text-foreground"><X className="size-4" /> Clear filters</button>
            </div>
            <div className="overflow-x-auto"><table className="w-full min-w-[1700px] text-sm"><thead><tr className="border-b-2 border-foreground/80 bg-muted/30 text-left text-sm uppercase tracking-wider text-muted-foreground"><th className="px-5 py-4">S/N</th><th className="px-5 py-4">Customer Type</th><th className="px-5 py-4">Source</th><th className="px-5 py-4">Passport</th><th className="px-5 py-4">MLS File No</th><th className="px-5 py-4">File Title</th><th className="px-5 py-4">Land Use</th><th className="px-5 py-4">TP No</th><th className="px-5 py-4">House No</th><th className="px-5 py-4">Plot No</th><th className="px-5 py-4">District</th></tr></thead><tbody>
              {visible.map((record, index) => <tr key={`${record.sn}-${index}`} className="border-b border-border/70 hover:bg-muted/20"><td className="px-5 py-5 text-lg">{record.sn}</td><td className="px-5 py-5 text-lg font-semibold">{record.type === 'Primary' ? 'Individual' : 'Corporate'}</td><td className="px-5 py-5"><StatusBadge tone="blue" dot={false}>{record.type === 'Primary' ? 'Conversion' : 'Direct Allocation'}</StatusBadge></td><td className="px-5 py-5"><Avatar name={record.applicant} /></td><td className="px-5 py-5 text-lg font-bold text-foreground">{record.mlsFileNo}</td><td className="max-w-72 px-5 py-5 text-lg">{record.applicant}</td><td className="px-5 py-5"><StatusBadge tone={landUseTone(record.landUse)} dot={false}>{record.landUse}</StatusBadge><div className="mt-1 text-xs font-semibold text-muted-foreground">{record.landUse}</div></td><td className="px-5 py-5 text-lg">N/A</td><td className="px-5 py-5 text-lg">N/A</td><td className="px-5 py-5 text-lg">N/A</td><td className="px-5 py-5 text-lg">N/A</td></tr>)}
              {!visible.length && <tr><td colSpan={11} className="px-5 py-16 text-center text-muted-foreground">No file numbers match your filters.</td></tr>}
            </tbody></table></div>
          </section>
        </div>
      </div>
      <Modal open={commissionOpen} onClose={() => setCommissionOpen(false)} title="Commission New File Number" description="Fill in the details to generate a new MLS file number" widthClass="max-w-5xl" footer={<div className="flex w-full items-center justify-between gap-3"><button type="button" onClick={() => setGenerated(preview)} className="rounded-md bg-orange-300 px-5 py-2 text-sm font-medium text-white">Override</button><button type="button" onClick={() => setCommissionOpen(false)} className="rounded-md border border-border px-6 py-2 text-sm">Cancel</button><button type="button" onClick={() => setGenerated(preview)} className="rounded-md bg-primary px-6 py-2 text-sm font-semibold text-primary-foreground">+ Generate</button></div>}>
        <div className="flex flex-col gap-5 p-5">
          <section className="rounded-lg border border-border bg-muted/20 p-4"><div className="flex items-center justify-between"><p className="font-semibold">ⓘ Application Type</p><Field label="SCHEDULES"><SelectInput value={schedule} onChange={(event) => handleScheduleChange(event.target.value as FileNoSchedule)}>{FILENO_SCHEDULES.map((item) => <option key={item}>{item}</option>)}</SelectInput></Field><Field label="FILE TYPE"><SelectInput value={commissionFileType} onChange={(event) => setCommissionFileType(event.target.value)}><option value="">Select File Type</option><option>Temporary</option><option>Extension</option><option>Miscellaneous</option><option>Change of Purpose</option><option>Resettlement</option><option>Re-grant</option><option>Re-issuance of FileNo</option><option>Recertification</option><option>Subdivision</option><option>Merger</option><option>Separation</option><option>Duplex</option></SelectInput></Field></div><div className="mt-4 flex flex-wrap items-center gap-6 border-t border-border pt-4"><label className="flex items-center gap-2"><input type="radio" defaultChecked name="application-type" /> Direct Allocation</label><label className="flex items-center gap-2"><input type="radio" name="application-type" /> Conversion</label></div><div className="mt-4 border-t border-border pt-4"><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Direct Allocation Type</p><div className="grid gap-2 sm:grid-cols-3">{['Default', 'Occupancy Permit (OP)', 'Allocation List'].map((item, index) => <label key={item} className="rounded-md border border-input bg-background px-3 py-2 text-sm"><input type="radio" name="allocation-type" defaultChecked={index === 0} /> <span className="ml-2">{item}</span></label>)}</div></div></section>
          <section className={`rounded-lg border p-4 ${batchMode ? 'border-primary/40 bg-primary/5' : 'border-primary/30 bg-primary/5'}`}><div className="flex items-center justify-between"><p className="font-semibold">▱ Batch Mode <span className="font-normal text-muted-foreground">(Generate multiple files at once)</span></p><button type="button" role="switch" aria-checked={batchMode} onClick={() => { setBatchMode((value) => !value); setBatchApplicant(0); setBatchLocation(0) }} className={`relative h-6 w-11 rounded-full transition-colors ${batchMode ? 'bg-primary' : 'bg-muted-foreground/30'}`}><span className={`absolute top-1 size-4 rounded-full bg-background transition-transform ${batchMode ? 'left-6' : 'left-1'}`} /></button></div>{batchMode && <div className="mt-4 border-t border-primary/20 pt-4"><Field label="Number of Files to Generate"><div className="flex items-center gap-3"><input type="number" min="1" max="200" value={batchCount} onChange={(event) => setBatchCount(String(Math.min(200, Math.max(1, Number(event.target.value) || 1))))} className="h-10 w-32 rounded-md border border-primary bg-background px-3" /><span className="text-sm text-muted-foreground">files (Max: 200)</span><span className="ml-auto text-sm text-primary">Serial Range: {batchMode ? `${sequence} - ${Number(sequence || 0) + Number(batchCount || 0) - 1}` : '-'}</span></div></Field><p className="mt-3 text-xs font-medium text-muted-foreground">ⓘ All files will share the same File Name (File Title) and Prefix. You can only add unique location details for each file (if need be)</p></div>}</section>
          <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-lg border border-border p-4"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold">⚙ File Options {batchMode && <span className="ml-2 rounded-full bg-primary/10 px-2 py-1 text-xs font-normal text-primary">Applicant {batchApplicant + 1} of {batchCount}</span>}</h3>{batchMode && <div className="flex gap-3 text-primary"><button type="button" aria-label="Previous applicant" onClick={() => setBatchApplicant((value) => Math.max(0, value - 1))}>‹</button><button type="button" aria-label="Next applicant" onClick={() => setBatchApplicant((value) => Math.min(Number(batchCount) - 1, value + 1))}>›</button></div>}</div>{batchMode && (<label className="mb-4 flex items-center gap-2 border-b border-border pb-3 text-xs"><input type="checkbox" /> Apply Applicant Details to All Files</label>)}<div className="grid gap-4 sm:grid-cols-2"><Field label="File Type"><SelectInput value={commissionFileType} onChange={(event) => setCommissionFileType(event.target.value)}><option value="">Normal File</option><option>Temporary</option><option>Extension</option><option>Miscellaneous</option><option>Change of Purpose</option><option>Resettlement</option><option>Re-grant</option><option>Re-issuance of FileNo</option><option>Recertification</option><option>Subdivision</option><option>Merger</option><option>Separation</option><option>Duplex</option></SelectInput></Field><Field label="File Name"><input placeholder="Enter file name" className="h-10 w-full rounded-md border border-input bg-background px-3" /></Field><Field label="Select Prefix"><SelectInput value={prefix} onChange={(event) => setPrefix(event.target.value as FileNoPrefix)}>{scheduleRule.prefixes.map((item) => <option key={item}>{item}</option>)}</SelectInput></Field><Field label="Select Land Use"><SelectInput value={landUse} onChange={(event) => setLandUse(event.target.value)}><option value="">(Auto-select)</option><option>Residential</option><option>Commercial</option><option>Industrial</option></SelectInput></Field><Field label="Purpose"><SelectInput><option>Select Purpose</option></SelectInput></Field><Field label="Customer Type"><SelectInput><option>Select Customer</option></SelectInput></Field><Field label="Gender"><SelectInput><option>Select Gender</option></SelectInput></Field><Field label="Phone No of Applicant *"><input placeholder="Enter Phone No" className="h-10 w-full rounded-md border border-input bg-background px-3" /></Field><Field label="Address of Applicant"><input placeholder="ENTER ADDRESS" className="h-10 w-full rounded-md border border-input bg-background px-3" /></Field></div></section>
            <div className="flex flex-col gap-5"><section className="rounded-lg border border-border p-4"><label className="flex items-start gap-2 text-sm"><input type="checkbox" /> <span><strong>This file has a Related File Number</strong><span className="block text-muted-foreground">Check this if this file is related to an existing file.</span></span></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Year"><input value="2026" readOnly className="h-10 w-full rounded-md border border-input bg-muted px-3" /></Field><Field label="Serial No."><input type="number" value={sequence} onChange={(event) => setSequence(event.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3" /></Field></div><div className="mt-4 rounded-lg border border-primary/30 bg-primary/5 p-4"><p className="font-medium">◉ Generated File Number Preview</p><p className="mt-3 rounded-md border border-primary bg-background p-4 text-center font-mono text-xl font-bold">{generated || preview}</p></div><p className="mt-4 rounded-md bg-muted p-3 font-mono">Tracking ID: <span className="text-destructive">--</span></p></section><section className="rounded-lg border border-border p-4"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold">⌖ Location Details {batchMode && <span className="ml-2 rounded-full bg-primary/10 px-2 py-1 text-xs font-normal text-primary">Entry {batchLocation + 1} of {batchCount}</span>}</h3>{batchMode && <div className="flex gap-3 text-primary"><button type="button" aria-label="Previous location" onClick={() => setBatchLocation((value) => Math.max(0, value - 1))}>‹</button><button type="button" aria-label="Next location" onClick={() => setBatchLocation((value) => Math.min(Number(batchCount) - 1, value + 1))}>›</button></div>}</div>{batchMode && (<label className="mb-4 flex items-center gap-2 border-b border-border pb-3 text-xs"><input type="checkbox" /> Apply Location to All Files</label>)}<div className="grid gap-4 sm:grid-cols-2"><Field label="TP Number"><input placeholder="Type to search TP" className="h-10 w-full rounded-md border border-input px-3" /></Field><Field label="House No"><input placeholder="Enter house number" className="h-10 w-full rounded-md border border-input px-3" /></Field><Field label="Plot Number"><input placeholder="Enter plot number" className="h-10 w-full rounded-md border border-input px-3" /></Field><Field label="District"><input placeholder="Search or select" className="h-10 w-full rounded-md border border-input px-3" /></Field><Field label="LGA"><SelectInput><option>Select LGA</option></SelectInput></Field><Field label="Location"><input placeholder="Filled from plot number, district & LGA" className="h-10 w-full rounded-md border border-input px-3 sm:col-span-2" /></Field></div></section></div></div>
          <section className="rounded-lg border border-border p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wider text-primary">⌖ Property Location Map</p><div className="flex gap-2"><button type="button" className="rounded-md border border-primary px-3 py-2 text-xs">Pin on Map</button><button type="button" className="rounded-md border border-border px-3 py-2 text-xs">Clear Pin</button></div></div><div className="mt-3 flex min-h-36 items-center justify-center rounded-md border border-dashed border-border text-sm text-muted-foreground">No map pin yet. Pick an LGA to pin automatically, or click Pin on Map to set one manually.</div></section>
        </div>
      </Modal>
    </AppShell>
  )
}

function SummaryCard({ icon: Icon, label, value, note, tone }: { icon: typeof FileCheck2; label: string; value: string; note: string; tone: 'blue' | 'green' | 'violet' }) {
  const styles = { blue: 'bg-blue-50 text-blue-700', green: 'bg-green-50 text-green-700', violet: 'bg-violet-50 text-violet-700' }
  return <div className="flex min-h-32 items-center gap-5 rounded-xl border border-border bg-background p-6 shadow-sm"><span className={`flex size-16 items-center justify-center rounded-xl ${styles[tone]}`}><Icon className="size-9" /></span><div><p className="text-xl text-muted-foreground">{label}</p><p className="text-4xl font-bold tracking-tight">{value}</p><p className="mt-1 text-base text-muted-foreground">{note}</p></div></div>
}
