'use client'

import { useEffect, useMemo, useState } from 'react'
import { ClipboardCheck, Download, FileSearch, Filter, Search, ShieldCheck, SlidersHorizontal, WalletCards, Plus, X, RotateCcw, Table2, LayoutGrid, ChevronDown, ExternalLink, Printer } from 'lucide-react'
import { AppShell } from '@/components/app-shell'
import { Avatar, Field, Modal, SearchBar, SectionCard, SectionHeader, SelectInput, StatTile, StatusBadge } from '@/components/system-admin/primitives'
import { LEGAL_SEARCH_RECORDS, OFFICIAL_REQUESTS, ON_PREMISE_REQUESTS, SEARCH_LAND_USES, SEARCH_LOCATIONS, SEARCH_TONES, filterRecords, type PropertyRecord } from '@/lib/legal-search-data'
import { SearchReport } from '@/components/legal-search/search-report'

const metrics = [
  { label: 'Records indexed', value: '4,297', tone: 'primary' as const },
  { label: 'Searches today', value: '38', tone: 'plain' as const },
  { label: 'Pending review', value: '07', tone: 'plain' as const },
]

function Hero({ kind, onNewSearch }: { kind: 'records' | 'official' | 'on-premise'; onNewSearch: () => void }) {
  const content = {
    records: { title: 'Property Records', description: 'Search indexed land records across Abia State with a complete audit trail.', icon: FileSearch },
    official: { title: 'Official Legal Search', description: 'Prepare verified property searches for filing, due diligence, and legal proceedings.', icon: ShieldCheck },
    'on-premise': { title: 'On-Premise Legal Search', description: 'Process counter-based, pay-per-search requests from the registry office.', icon: WalletCards },
  }[kind]
  const Icon = content.icon
  return <div className="overflow-hidden rounded-2xl border border-primary/30 bg-gradient-to-br from-primary/25 via-card to-card p-6 shadow-sm md:p-8">
    <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
      <div className="flex items-start gap-4"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-primary text-primary-foreground shadow-lg shadow-primary/20"><Icon className="h-7 w-7" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Legal Search</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-balance">{content.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{content.description}</p></div></div>
      <div className="flex gap-2"><button type="button" onClick={onNewSearch} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground hover:bg-primary/90"><Search className="h-4 w-4" /> New search</button><button type="button" className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-4 py-2.5 text-sm font-medium hover:bg-muted"><Download className="h-4 w-4" /> Export</button></div>
    </div>
  </div>
}

function FilterBar({ onChange }: { onChange: (value: string) => void }) {
  const [query, setQuery] = useState('')
  const [location, setLocation] = useState('All locations')
  const [landUse, setLandUse] = useState('All land uses')
  const [status, setStatus] = useState('All statuses')
  const apply = (next: Partial<{ query: string; location: string; landUse: string; status: string }>) => {
    const values = { query, location, landUse, status, ...next }
    setQuery(values.query); setLocation(values.location); setLandUse(values.landUse); setStatus(values.status)
    onChange(JSON.stringify(values))
  }
  return <div className="grid gap-3 border-b border-border bg-muted/20 p-4 md:grid-cols-[minmax(220px,1fr)_repeat(3,minmax(140px,180px))]"><SearchBar value={query} onChange={(value) => apply({ query: value })} placeholder="File number, owner, property…" /><SelectInput value={location} onChange={(e) => apply({ location: e.target.value })}>{SEARCH_LOCATIONS.map((value) => <option key={value}>{value}</option>)}</SelectInput><SelectInput value={landUse} onChange={(e) => apply({ landUse: e.target.value })}>{SEARCH_LAND_USES.map((value) => <option key={value}>{value}</option>)}</SelectInput><SelectInput value={status} onChange={(e) => apply({ status: e.target.value })}>{['All statuses', 'Verified', 'Pending', 'Archived', 'Flagged'].map((value) => <option key={value}>{value}</option>)}</SelectInput></div>
}

function RecordsTable({ records }: { records: PropertyRecord[] }) {
  return <SectionCard className="overflow-hidden"><SectionHeader title="Property record index" description={`${records.length} records match the active filters.`} actions={<button type="button" className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-medium hover:bg-muted"><Filter className="h-3.5 w-3.5" /> Advanced filters</button>} /><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-muted/30 text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-3">File number</th><th className="px-5 py-3">Property / owner</th><th className="px-5 py-3">Location</th><th className="px-5 py-3">Land use</th><th className="px-5 py-3">Instrument</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Updated</th></tr></thead><tbody className="divide-y divide-border">{records.map((record) => <tr key={record.id} className="transition-colors hover:bg-muted/20"><td className="px-5 py-4 font-mono text-xs font-semibold text-primary">{record.fileNo}</td><td className="px-5 py-4"><p className="font-medium">{record.property}</p><div className="mt-1 flex items-center gap-2 text-xs text-muted-foreground"><Avatar name={record.owner} className="h-6 w-6 text-[10px]" />{record.owner}</div></td><td className="px-5 py-4 text-muted-foreground">{record.location}</td><td className="px-5 py-4">{record.landUse}</td><td className="px-5 py-4 text-muted-foreground">{record.instrument}</td><td className="px-5 py-4"><StatusBadge tone={SEARCH_TONES[record.status]}>{record.status}</StatusBadge></td><td className="px-5 py-4 text-xs text-muted-foreground">{record.lastUpdated}</td></tr>)}</tbody></table></div></SectionCard>
}

const dynamicFilters = ['Grantor Name', 'Grantee Name', 'Schedule Name', 'Layout Name', 'LGA / City ID', 'District ID', 'Plot Number', 'Plot Size', 'Parent Registration No.', 'Root Registration No.', 'Approval Status', 'Transaction Type']

type SearchRecord = PropertyRecord & Partial<Record<'ABIAGISFileNo' | 'newABIAGISFileNo' | 'guarantor' | 'guarantee' | 'lga' | 'plotNumber' | 'registrationParticulars' | 'particulars' | 'size' | 'caveat' | 'type' | 'created' | 'propertyId' | 'grantor' | 'grantee' | 'scheduleName' | 'layoutName' | 'plotSize' | 'approved' | 'transactionType', string>>

function LegacySearchReport({ record, official, onClose }: { record: SearchRecord; official: boolean; onClose: () => void }) {
  const transactions = [
    { type: record.transactionType ?? record.instrument ?? 'Property transaction', party1: record.grantor ?? 'Abia State Government', party2: record.grantee ?? record.owner, date: record.created ?? 'Not recorded', particulars: record.particulars ?? 'Transaction history record', caveat: record.caveat ?? 'None' },
  ]
  return <Modal open onClose={onClose} title="Search Report Preview" widthClass="max-w-[95vw]" footer={<div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-border px-4 py-2 text-sm font-medium hover:bg-muted">Close</button><button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-2 text-sm font-semibold text-primary-foreground"><Printer className="h-4 w-4" /> Print report</button></div>}>
    <article className="relative mx-auto min-h-[760px] max-w-[1120px] overflow-hidden bg-card px-8 py-6 text-foreground shadow-sm print:min-h-screen print:shadow-none">
      {official && <div className="pointer-events-none absolute inset-0 z-0 flex items-center justify-center"><span className="-rotate-30 select-none whitespace-nowrap text-[clamp(3rem,9vw,8rem)] font-black tracking-[0.16em] text-destructive/10">FOR OFFICIAL PURPOSE</span></div>}
      <div className="relative z-10">
        <header className="border-b-2 border-foreground pb-2"><div className="text-center"><p className="text-sm font-bold uppercase tracking-wide text-primary">Abia State Ministry of Lands and Housing</p><h1 className="mt-1 text-xl font-bold">LEGAL SEARCH REPORT</h1><p className="mt-1 text-sm font-bold underline">{official ? 'Official Search (For Filing Purpose)' : 'On-Premise Pay-per-Search'}</p></div><p className="mt-2 text-right text-xs font-semibold">Date: {new Date().toLocaleDateString('en-GB')}</p></header>
        <div className="mt-3 inline-block border border-foreground px-2 py-1 text-xs font-bold">Property Details</div>
        <div className="mt-1 grid grid-cols-2 gap-x-8 gap-y-2 border-b border-border pb-3 text-xs md:grid-cols-4"><ReportField label="Property ID" value={record.propertyId ?? record.id} /><ReportField label="File Number" value={record.fileNo} /><ReportField label="Current Holder" value={record.grantee ?? record.owner} /><ReportField label="LGA / City" value={record.lga ?? 'Abia State'} /><ReportField label="Schedule" value={record.scheduleName ?? record.property} /><ReportField label="Layout" value={record.layoutName ?? record.location} /><ReportField label="Plot Number" value={record.plotNumber ?? 'Not recorded'} /><ReportField label="Plot Size" value={record.plotSize ?? record.size ?? 'Not recorded'} /><ReportField label="Approval" value={record.approved ?? record.status} /><ReportField label="Parent Registration" value={record.particulars ?? 'Not recorded'} /></div>
        <div className="mt-3 inline-block border border-foreground px-2 py-1 text-xs font-bold">File History</div>
        <div className="mt-1 overflow-x-auto"><table className="w-full min-w-[850px] table-fixed border-collapse text-[10px]"><thead><tr className="border-b-2 border-foreground text-left"><th className="w-8 py-1">S/N</th><th className="w-[15%] py-1">File No.</th><th className="w-[17%] py-1">Instrument / Transaction Type</th><th className="w-[18%] py-1">Party 1</th><th className="w-[18%] py-1">Party 2</th><th className="w-[12%] py-1">Transaction Date</th><th className="w-[15%] py-1">Particulars</th><th className="w-[8%] py-1">Caveat</th></tr></thead><tbody>{transactions.map((transaction, index) => <tr key={`${transaction.type}-${index}`} className="border-b border-border align-top"><td className="py-2">{index + 1}</td><td className="py-2 font-mono">{record.fileNo}</td><td className="py-2">{transaction.type}</td><td className="py-2">{transaction.party1}</td><td className="py-2">{transaction.party2}</td><td className="py-2">{transaction.date}</td><td className="py-2">{transaction.particulars}</td><td className="py-2">{transaction.caveat}</td></tr>)}</tbody></table></div>
        <div className="mt-5 border-t border-foreground pt-3"><span className="border border-foreground px-2 py-1 text-xs font-bold">Remarks</span><p className="mt-3 text-xs font-semibold text-primary">This search report is prepared from the available Abia State property and transaction records.</p><p className="mt-4 text-center text-[10px] font-bold italic">N.B: This search report is deduced based on the available records from the file and does not represent any document in possession of any body.</p></div>
        <div className="mt-8 grid grid-cols-3 gap-6 text-[10px]"><div>Name: ____________________<br /><br />Rank: ____________________<br /><br />Sign / Date: _______________</div><div>Verified by: _______________<br /><br />Rank: ____________________<br /><br />Sign / Date: _______________</div><div>Sign / Date: _______________<br /><br /><strong>Director Deeds</strong><br /><span>(for Permanent Secretary / Commissioner)</span></div></div>
        <div className="mt-6 flex justify-between border-t border-foreground pt-2 text-[9px] text-muted-foreground"><span>Abia State Land Administration and E-Governance System</span><span>{official ? 'Generated for official filing purpose' : 'Generated via on-premise pay-per-search'}</span></div>
      </div>
    </article>
  </Modal>
}

function ReportField({ label, value }: { label: string; value: string | number }) { return <div><span className="font-bold">{label}: </span><strong>{value || 'Not recorded'}</strong></div> }

function SearchModal({ open, onClose, kind }: { open: boolean; onClose: () => void; kind: 'official' | 'on-premise' }) {
  const [fileNumber, setFileNumber] = useState('')
  const [ABIAGISFileNo, setABIAGISFileNo] = useState('')
  const [filtersOpen, setFiltersOpen] = useState(true)
  const [view, setView] = useState<'table' | 'cards'>('table')
  const [activeExtra, setActiveExtra] = useState<string[]>([])
  const [searched, setSearched] = useState(false)
  const [records, setRecords] = useState<SearchRecord[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [source, setSource] = useState<'mssql' | 'demo'>('demo')
  const [reportRecord, setReportRecord] = useState<SearchRecord | null>(null)
  const matching = useMemo(() => records, [records])
  useEffect(() => {
    if (!searched) return
    const controller = new AbortController()
    setLoading(true); setError('')
    fetch(`/api/legal-search/records?search=${encodeURIComponent(`${fileNumber} ${ABIAGISFileNo}`.trim())}`, { signal: controller.signal })
      .then(async (response) => { const payload = await response.json(); if (!response.ok || !payload.ok) throw new Error('The Abia property records could not be loaded.'); setRecords((payload.records ?? []).map((record: SearchRecord) => ({ ...record, id: String(record.id ?? record.fileNo), fileNo: record.fileNo ?? '—', property: record.property ?? 'Property record', owner: record.owner ?? 'Not recorded', location: record.location ?? record.lga ?? 'Abia State', landUse: record.landUse ?? '���', instrument: record.particulars ?? record.type ?? 'Transaction record', status: record.status ?? 'Pending', lastUpdated: record.created ?? '—' }))); setSource(payload.source === 'mssql' ? 'mssql' : 'demo') })
      .catch((reason) => { if (reason.name !== 'AbortError') { setError('Unable to load Abia property records. Check the SQL Server connection and try again.'); setRecords([]) } })
      .finally(() => setLoading(false))
    return () => controller.abort()
  }, [searched, fileNumber, ABIAGISFileNo])
  const reset = () => { setFileNumber(''); setABIAGISFileNo(''); setActiveExtra([]); setSearched(false); setRecords([]); setError('') }
  return <Modal open={open} onClose={onClose} title="Search Land Records" widthClass="max-w-[95vw]" footer={<div className="flex items-center justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-border px-4 py-2 text-sm font-medium hover:bg-muted">Close</button><button type="button" onClick={() => setSearched(true)} className="inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-2 text-sm font-semibold text-primary-foreground"><Search className="h-4 w-4" /> Run search</button></div>}>
    <div className="flex max-h-[72vh] flex-col overflow-hidden">
      <div className="border-b border-border bg-muted/20 p-4">
        <p className="mb-3 text-xs text-muted-foreground">{kind === 'official' ? 'Official search for filing, due diligence, and legal proceedings.' : 'Paid on-premise search processed through the registry counter.'}</p>
        <div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold">Search Filters</h3><button type="button" onClick={() => setFiltersOpen(!filtersOpen)} className="rounded-lg border border-border px-3 py-1.5 text-xs font-medium">{filtersOpen ? 'Collapse Filters' : 'Expand Filters'}</button></div>
        {filtersOpen ? <div className="flex flex-wrap items-center gap-2"><div className="flex items-center gap-2"><span className="rounded-full border border-border px-3 py-1 text-xs">File Number</span><input value={fileNumber} onChange={(e) => setFileNumber(e.target.value)} placeholder="Enter file number" className="w-52 rounded-lg border border-input bg-background px-3 py-2 text-sm" /><button type="button" aria-label="Clear file number" onClick={() => setFileNumber('')}><X className="h-4 w-4 text-muted-foreground" /></button></div><div className="flex items-center gap-2"><span className="rounded-full border border-border px-3 py-1 text-xs">Parent File Number</span><input value={ABIAGISFileNo} onChange={(e) => setABIAGISFileNo(e.target.value)} placeholder="Enter parent file number" className="w-56 rounded-lg border border-input bg-background px-3 py-2 text-sm" /><button type="button" aria-label="Clear ABIAGIS file number" onClick={() => setABIAGISFileNo('')}><X className="h-4 w-4 text-muted-foreground" /></button></div><div className="relative"><select aria-label="Add filter" onChange={(e) => { if (e.target.value && !activeExtra.includes(e.target.value)) setActiveExtra([...activeExtra, e.target.value]); e.currentTarget.value = '' }} className="rounded-lg border border-input bg-background px-3 py-2 text-sm"><option value="">+ Add Filter</option>{dynamicFilters.filter((item) => !activeExtra.includes(item)).map((item) => <option key={item}>{item}</option>)}</select></div><button type="button" onClick={reset} className="ml-auto inline-flex items-center gap-1 rounded-lg border border-border px-3 py-2 text-xs font-medium"><RotateCcw className="h-3.5 w-3.5" /> Reset</button>{activeExtra.map((filter) => <span key={filter} className="rounded-full bg-primary/10 px-3 py-1 text-xs text-primary">{filter}</span>)}</div> : <div className="flex items-center justify-between text-xs text-muted-foreground">Filtered by: File Number, ABIAGIS File No.<button type="button" onClick={reset} className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-1.5 font-medium"><RotateCcw className="h-3.5 w-3.5" /> Reset</button></div>}
        <div className="mt-4 flex items-center justify-between"><span className="text-xs text-muted-foreground">{searched ? matching.length : 0} results found {searched && <span className="ml-2 rounded-full bg-primary/10 px-2 py-1 text-primary">{source === 'mssql' ? 'Abia MSSQL' : 'Demo data'}</span>}</span><div className="flex rounded-lg border border-border p-1"><button type="button" onClick={() => setView('table')} className={`rounded-md px-3 py-1.5 text-xs ${view === 'table' ? 'bg-primary text-primary-foreground' : ''}`}><Table2 className="mr-1 inline h-3.5 w-3.5" />Table View</button><button type="button" onClick={() => setView('cards')} className={`rounded-md px-3 py-1.5 text-xs ${view === 'cards' ? 'bg-primary text-primary-foreground' : ''}`}><LayoutGrid className="mr-1 inline h-3.5 w-3.5" />Card View</button></div></div>
      </div>
      <div className="flex-1 overflow-auto p-5">{loading ? <div className="py-16 text-center text-sm text-muted-foreground">Searching Abia State property records…</div> : error ? <div className="rounded-xl border border-destructive/30 bg-destructive/10 p-5 text-sm text-destructive">{error}</div> : !searched ? <div className="py-16 text-center text-sm text-muted-foreground">Enter filters and run a search to view Abia State land records.</div> : matching.length === 0 ? <div className="py-16 text-center text-sm text-muted-foreground">No results found. Please try a different search.</div> : view === 'cards' ? <div className="grid gap-4 md:grid-cols-2">{matching.map((record) => <div key={record.id} className="rounded-xl border border-border p-4"><div className="flex items-center justify-between"><span className="font-mono text-sm font-semibold text-primary">{record.fileNo}</span><StatusBadge tone={SEARCH_TONES[record.status]}>{record.status}</StatusBadge></div><p className="mt-3 font-medium">{record.property}</p><p className="mt-1 text-sm text-muted-foreground">{record.owner} · {record.location}</p><button type="button" onClick={() => setReportRecord(record)} className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-primary">View report <ExternalLink className="h-3 w-3" /></button></div>)}</div> : <div className="overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-muted/30 text-xs uppercase tracking-wider text-muted-foreground"><tr>{['Parent File No.', 'File Number ID', 'Grantor', 'Grantee', 'Schedule', 'Layout', 'LGA / City ID', 'District ID', 'Plot No.', 'Plot Size', 'Approval', 'Transaction Type', 'Actions'].map((heading) => <th key={heading} className="px-4 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{matching.map((record) => <tr key={record.id} className="hover:bg-muted/20"><td className="px-4 py-3 font-mono text-xs font-semibold text-primary">{record.fileNo}</td><td className="px-4 py-3 text-xs">{record.ABIAGISFileNo ?? '—'}</td><td className="px-4 py-3 text-xs">{record.newABIAGISFileNo ?? '—'}</td><td className="px-4 py-3">{record.guarantor ?? record.owner}</td><td className="px-4 py-3">{record.guarantee ?? '—'}</td><td className="px-4 py-3">{record.lga ?? '—'}</td><td className="px-4 py-3">{record.location}</td><td className="px-4 py-3">{record.plotNumber ?? '—'}</td><td className="px-4 py-3 text-xs">{record.registrationParticulars ?? record.instrument}</td><td className="px-4 py-3">{record.size ?? '—'}</td><td className="px-4 py-3">{record.caveat ?? 'No'}</td><td className="px-4 py-3"><button type="button" onClick={() => setReportRecord(record)} className="text-xs font-semibold text-primary">View report</button></td></tr>)}</tbody></table></div>}</div>
    </div>
    {reportRecord && <SearchReport record={reportRecord} official={kind === 'official'} onClose={() => setReportRecord(null)} />}
  </Modal>
}

function LegalSearchDashboard({ kind, onNewSearch }: { kind: 'official' | 'on-premise'; onNewSearch: () => void }) {
  const official = kind === 'official'
  const title = official ? 'Official Search' : 'On-Premise Search'
  const subtitle = official ? 'Find legal records for official purposes' : 'Find legal records at the registry counter'
  const description = official
    ? 'Conduct legal searches for official purposes with extended access to records.'
    : 'Conduct paid legal searches for clients using the on-premise registry service.'
  const activities = official ? ['File Search #2024', 'File Search #2025', 'File Search #2026', 'File Search #2027'] : ['Counter Search #1087', 'Counter Search #1086', 'Counter Search #1085', 'Counter Search #1084']
  return <div className="space-y-6">
    <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
      <SectionCard className="overflow-hidden"><div className="p-6"><div className="mb-1 flex items-center gap-2"><Search className="h-5 w-5 text-primary" /><h3 className="text-lg font-semibold">{title}</h3></div><p className="mb-4 text-sm text-muted-foreground">{subtitle}</p><p className="mb-4 text-sm leading-6 text-muted-foreground">{description}</p><button type="button" onClick={onNewSearch} className="inline-flex w-full items-center justify-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"><FileSearch className="h-4 w-4" /> Search Records</button></div></SectionCard>
      <SectionCard className="overflow-hidden"><div className="p-6"><div className="mb-1 flex items-center gap-2"><ClipboardCheck className="h-5 w-5 text-primary" /><h3 className="text-lg font-semibold">Recent Searches</h3></div><p className="mb-4 text-sm text-muted-foreground">View your recent legal searches</p><p className="mb-4 text-sm leading-6 text-muted-foreground">Access recent searches to quickly return to previously viewed property records.</p><button type="button" className="inline-flex w-full items-center justify-center gap-2 rounded-md border border-border bg-card px-4 py-2 text-sm font-medium hover:bg-muted"><ClipboardCheck className="h-4 w-4" /> View Reports</button></div></SectionCard>
      <SectionCard className="overflow-hidden"><div className="p-6"><div className="mb-1 flex items-center gap-2"><ExternalLink className="h-5 w-5 text-primary" /><h3 className="text-lg font-semibold">Online Portal</h3></div><p className="mb-4 text-sm text-muted-foreground">Access the online legal search portal</p><p className="mb-4 text-sm leading-6 text-muted-foreground">Switch to the online portal for remote access to legal search services.</p><button type="button" className="inline-flex w-full items-center justify-center gap-2 rounded-md border border-border bg-card px-4 py-2 text-sm font-medium hover:bg-muted"><ExternalLink className="h-4 w-4" /> Go to Online Portal</button></div></SectionCard>
    </div>
    <SectionCard className="overflow-hidden"><div className="p-6"><div className="mb-1 flex items-center gap-2"><SlidersHorizontal className="h-5 w-5 text-primary" /><h3 className="text-lg font-semibold">Search Trends</h3></div><p className="mb-6 text-sm text-muted-foreground">{official ? 'Official search volume over the past 12 months' : 'On-premise search volume over the past 12 months'}</p><div className="flex h-56 items-end gap-3 border-b border-border px-2">{[38, 52, 44, 68, 58, 76, 64, 82, 70, 91, 78, 96].map((height, index) => <div key={index} className="group flex flex-1 flex-col items-center gap-2"><div className="w-full max-w-12 rounded-t-md bg-primary/70 transition-colors group-hover:bg-primary" style={{ height: `${height * 1.55}px` }} /><span className="text-[10px] text-muted-foreground">{['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][index]}</span></div>)}</div></div></SectionCard>
    <div className="grid grid-cols-1 gap-6 md:grid-cols-2"><SectionCard><div className="p-6"><h3 className="mb-1 text-lg font-semibold">Search Statistics</h3><p className="mb-4 text-sm text-muted-foreground">Key metrics for {official ? 'official' : 'on-premise'} searches</p><div className="space-y-4">{[[official ? 'Total Searches (This Month)' : 'Paid Searches (This Month)', official ? '24' : '38'], ['Average Search Time', '3.2 minutes'], ['Success Rate', '92%'], ['Most Common Search Type', 'File Number']].map(([label, value]) => <div key={label} className="flex items-center justify-between border-b border-border/60 pb-3 text-sm last:border-0"><span className="font-medium">{label}</span><span className="font-bold">{value}</span></div>)}</div></div></SectionCard><SectionCard><div className="p-6"><h3 className="mb-1 text-lg font-semibold">Recent Activity</h3><p className="mb-4 text-sm text-muted-foreground">Latest {official ? 'official' : 'on-premise'} search activities</p><div className="space-y-4">{activities.map((activity, index) => <div key={activity} className="flex items-center justify-between border-b border-border/60 pb-3 last:border-0"><div><p className="font-medium">{activity}</p><p className="text-sm text-muted-foreground">{['Just now', '2 hours ago', 'Yesterday', '3 days ago'][index]}</p></div><StatusBadge tone="green">Completed</StatusBadge></div>)}</div></div></SectionCard></div>
  </div>
}

function RequestTable({ kind }: { kind: 'official' | 'on-premise' }) {
  const official = kind === 'official'
  const rows = official ? OFFICIAL_REQUESTS : ON_PREMISE_REQUESTS
  return <SectionCard className="overflow-hidden"><SectionHeader title={official ? 'Official search requests' : 'Counter requests'} description={official ? 'Search certificates prepared for official filing purposes.' : 'Requests received from registry counters and pay-per-search desks.'} /><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-muted/30 text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-3">Reference</th><th className="px-5 py-3">Requester</th><th className="px-5 py-3">{official ? 'Purpose' : 'Counter'}</th><th className="px-5 py-3">{official ? 'Fee' : 'Token'}</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Submitted</th></tr></thead><tbody className="divide-y divide-border">{rows.map((row) => <tr key={row.id} className="hover:bg-muted/20"><td className="px-5 py-4"><p className="font-mono text-xs font-semibold text-primary">{row.reference}</p><p className="mt-1 text-xs text-muted-foreground">{row.id}</p></td><td className="px-5 py-4 font-medium">{row.requester}</td><td className="px-5 py-4 text-muted-foreground">{'purpose' in row ? row.purpose : row.counter}</td><td className="px-5 py-4 font-medium">{'fee' in row ? row.fee : row.token}</td><td className="px-5 py-4"><StatusBadge tone={row.status === 'Completed' || row.status === 'Ready' ? 'green' : row.status === 'Pending payment' ? 'amber' : 'blue'}>{row.status}</StatusBadge></td><td className="px-5 py-4 text-xs text-muted-foreground">{row.submitted}</td></tr>)}</tbody></table></div></SectionCard>
}

export function LegalSearchWorkspace({ kind }: { kind: 'records' | 'official' | 'on-premise' }) {
  const [filterState, setFilterState] = useState({ query: '', location: 'All locations', landUse: 'All land uses', status: 'All statuses' })
  const [searchOpen, setSearchOpen] = useState(false)
  const visibleRecords = useMemo(() => filterRecords(LEGAL_SEARCH_RECORDS, filterState.query, filterState.location, filterState.landUse, filterState.status), [filterState])
  const handleFilter = (value: string) => { try { setFilterState(JSON.parse(value)) } catch {} }
  const title = kind === 'records' ? 'Property Records' : kind === 'official' ? 'Official Legal Search' : 'On-Premise Legal Search'
  return <AppShell title={title} subtitle="Search and manage Abia State property records with a traceable legal workflow." metrics={metrics}><div className="mx-auto max-w-[1500px] space-y-6">{kind === 'records' ? <><Hero kind={kind} onNewSearch={() => setSearchOpen(true)} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatTile icon={FileSearch} label="Indexed property records" value="4,297" hint="+12% this month" tone="green" /><StatTile icon={ShieldCheck} label="Verified records" value="3,814" hint="Across all zones" tone="blue" /><StatTile icon={ClipboardCheck} label="Pending review" value="07" hint="Needs attention" tone="amber" /><StatTile icon={SlidersHorizontal} label="Searches today" value="38" hint="Current period" tone="violet" /></div><FilterBar onChange={handleFilter} /><RecordsTable records={visibleRecords} /></> : <LegalSearchDashboard kind={kind} onNewSearch={() => setSearchOpen(true)} />}</div><SearchModal open={searchOpen} onClose={() => setSearchOpen(false)} kind={kind === 'records' ? 'official' : kind} /></AppShell>
}
